# Generated by Django 2.1.4 on 2018-12-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20181217_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaces',
            name='tenif',
            field=models.TextField(blank=True, db_column='TenIF', null=True),
        ),
    ]
